# Generated by Django 5.2.7 on 2025-10-16 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('RIDE_PATTERNS', 'Ride Patterns'), ('DRIVER_PERFORMANCE', 'Driver Performance'), ('REVENUE', 'Revenue Summary'), ('TRAFFIC', 'Traffic Analysis'), ('USER_BEHAVIOR', 'User Behavior'), ('CUSTOM', 'Custom Report')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('report_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['report_type', '-created_at'], name='analytics_a_report__6da31a_idx')],
            },
        ),
    ]
