# Generated by Django 5.2.6 on 2025-09-22 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('is_online', models.BooleanField(default=True)),
                ('speed_kmh', models.FloatField(default=0, help_text='Last reported speed')),
                ('heading', models.FloatField(blank=True, help_text='Degrees 0-359', null=True)),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'locations_driver_location',
                'indexes': [models.Index(fields=['is_online', 'updated_at'], name='locations_d_is_onli_b35b34_idx'), models.Index(fields=['lat', 'lng'], name='locations_d_lat_86ac4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('speed_kmh', models.FloatField(default=0)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'locations_location_ping',
                'indexes': [models.Index(fields=['driver', 'created_at'], name='locations_l_driver__151764_idx')],
            },
        ),
    ]
