# Generated by Django 5.2.7 on 2025-10-16 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('RIDE_REQUEST', 'Ride Request'), ('RIDE_ACCEPTED', 'Ride Accepted'), ('DRIVER_ARRIVING', 'Driver Arriving'), ('RIDE_STARTED', 'Ride Started'), ('RIDE_COMPLETED', 'Ride Completed'), ('RIDE_CANCELLED', 'Ride Cancelled'), ('PAYMENT_SUCCESS', 'Payment Successful'), ('PAYMENT_FAILED', 'Payment Failed'), ('DRIVER_NEARBY', 'Driver Nearby')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RideTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed_kmh', models.FloatField(default=0)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.AddField(
            model_name='ride',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_rides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='current_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Current driver location during ride', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='current_lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Current driver location during ride', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='driver_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='driver_rating',
            field=models.IntegerField(blank=True, help_text="Driver's rating of rider (1-5)", null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='final_fare',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual fare charged in RWF', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='payment_method',
            field=models.CharField(choices=[('MTN_MOMO', 'MTN Mobile Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('CASH', 'Cash'), ('CARD', 'Card')], default='MTN_MOMO', max_length=20),
        ),
        migrations.AddField(
            model_name='ride',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Mobile money transaction reference', max_length=100),
        ),
        migrations.AddField(
            model_name='ride',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='ride',
            name='reported_to_rtda',
            field=models.BooleanField(default=False, help_text='Whether ride has been reported to RTDA'),
        ),
        migrations.AddField(
            model_name='ride',
            name='rider_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='rider_rating',
            field=models.IntegerField(blank=True, help_text="Rider's rating of driver (1-5)", null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='rtda_report_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='fare_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated fare in RWF', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('SEARCHING', 'Searching for Driver'), ('ACCEPTED', 'Accepted'), ('DRIVER_ARRIVING', 'Driver Arriving'), ('ARRIVED', 'Driver Arrived'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], db_index=True, default='REQUESTED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['rider', '-created_at'], name='rides_ride_rider_i_f65512_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['driver', '-created_at'], name='rides_ride_driver__2fafcd_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status', '-created_at'], name='rides_ride_status_bb800a_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['payment_status'], name='rides_ride_payment_c94039_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['created_at'], name='rides_ride_created_fc9acb_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='rides.ride'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ridetracking',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_points', to='rides.ride'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='rides_notif_user_id_2e1596_idx'),
        ),
        migrations.AddIndex(
            model_name='ridetracking',
            index=models.Index(fields=['ride', '-timestamp'], name='rides_ridet_ride_id_010bdf_idx'),
        ),
    ]
